# add configs to switch between local and server settings
services:
  cassandra:
    image: "cassandra:latest"
    ports:
      - "9042:9042"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  edge:
    build: ./Api
    ports:
      - "5221:80"
  web:
    build: ./frontend
    ports:
      - "8080:80"
